---
- name: "config.credential_type: [ {{ tower_config_setting_credential_type.name }} ]"
  tower_credential_type:
    tower_host: "{{ tower_config.host | default(omit) }}"
    tower_username: "{{ tower_config.username | default(omit) }}"
    tower_password: "{{ tower_config.password | default(omit) }}"
    tower_verify_ssl: "{{ tower_config.verify_ssl | default(omit) }}"
    name: "{{ tower_config_setting_credential_type.name }}"
    description: "{{ tower_config_setting_credential_type.description | default(omit) }}"
    kind: cloud
    inputs: "{{ tower_config_setting_credential_type.inputs | default(omit) }}"
    injectors: "{{ tower_config_setting_credential_type.injectors | default(omit) }}"
    state: "{{ tower_config_setting_credential_type.state | default(omit) }}"
