---
- name: "config.organization: Ensure state of job_template: [ {{ tower_config_organization_job_template.name }} ]"
  tower_job_template:
    tower_host: "{{ tower_config.host }}"
    tower_username: "{{ tower_config.username }}"
    tower_password: "{{ tower_config.password }}"
    tower_verify_ssl: "{{ tower_config.verify_ssl|bool }}"
    name: "{{ tower_config_organization_job_template.name }}"
    playbook: "{{ tower_config_organization_job_template.playbook }}"
    project:  "{{ tower_config_organization_job_template.project }}"
    description: "{{ tower_config_organization_job_template.description | default(omit) }}"
    job_type: "{{ tower_config_organization_job_template.job_type | default('run') }}"
    ask_job_type: "{{ tower_config_organization_job_template.ask_job_type | default(omit) }}"
    credential: "{{ tower_config_organization_job_template.credential | default(omit) }}"
    vault_credential: "{{ tower_config_organization_job_template.vault_credential | default(omit) }}"
    ask_credential: "{{ tower_config_organization_job_template.ask_credential | default(omit) }}"
    inventory:  "{{ tower_config_organization_job_template.inventory }}"
    ask_inventory: "{{ tower_config_organization_job_template.ask_inventory | default(omit) }}"
    extra_vars_path: "{{ tower_config_organization_job_template.extra_vars_path | default(omit) }}"
    ask_extra_vars: "{{ tower_config_organization_job_template.ask_extra_vars | default(omit) }}"
    job_tags: "{{ tower_config_organization_job_template.job_tags | default(omit) }}"
    ask_tags: "{{ tower_config_organization_job_template.ask_tags | default(omit) }}"
    skip_tags: "{{ tower_config_organization_job_template.skip_tags | default(omit) }}"
    become_enabled: "{{ tower_config_organization_job_template.become_enabled | default(omit) }}"
    forks: "{{ tower_config_organization_job_template.forks | default(omit) }}"
    host_config_key: "{{ tower_config_organization_job_template.host_config_key | default(omit) }}"
    limit: "{{ tower_config_organization_job_template.limit | default(omit) }}"
#    ask_limit_on_launch: "{{ tower_config_organization_job_template.ask_limit_on_launch | default(omit) }}"
    verbosity: "{{ tower_config_organization_job_template.verbosity | default(omit) }}"
    state: "{{ tower_config_organization_job_template.state | default(omit) }}"
