---
- name: "config.setting-cli: Process [ license ]"
  include_tasks: "setting/license.yml"
  when: tower_config.setting.license is defined

  - name: "config.setting-cli: Process[ system ]"
  include_tasks: "setting/system.yml"
  when: tower_config.setting.system is defined
